include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # warning'leri error gibi treat et — CI'da fail olur
    invalid_assignment: error
    missing_required_param: error
    missing_return: error

  exclude:
    - "**/*.g.dart"          # Hive-generated
    - "**/*.freezed.dart"    # freezed-generated (ileride)
    - "build/**"

linter:
  rules:
    # Önerilen ek kurallar
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_print: true
    require_trailing_commas: true
    use_super_parameters: true
    unawaited_futures: true
